---
# bootstrap.yml has to be run before this playbook
- name: Setup for all hosts
  hosts: all
  pre_tasks:
      - name: Update pacman cache
        become: true
        pacman:
            update_cache: yes
        changed_when: false
        when: ansible_facts.distribution == "Archlinux"

      - name: Update apt cache
        become: true
        apt:
            update_cache: yes
            cache_valid_time: 3600
        when: ansible_facts.distribution == "Ubuntu"

  roles:
      - sshd
      - role: package-group
        group: "base_utils"
      - role: package-group
        group: "net_utils"
      - role: package-group
        group: "system_utils"
      - role: package-group
        group: "development_utils"

- hosts: laptop
  gather_facts: no
  roles:
      - role: package-group
        group: "desktop"
      - fonts
