---
# bootstrap.yml has to be run before this playbook
- name: Setup for all hosts
  hosts: all
  pre_tasks:
    - name: Update pacman cache
      become: yes
      pacman:
        update_cache: yes
      changed_when: false
      when: ansible_facts.distribution == "Archlinux"

- hosts: all
  gather_facts: no
  roles:
    - { role: packages, packages: "{{ host_packages }}" }
    - { role: services, services: "{{ host_services }}" }
