---
- name: "Install packages on ArchLinux : {{ packages|join(', ') }}"
  become: true
  pacman:
      name: "{{ packages }}"
      state: latest
  when: ansible_facts.distribution == "Archlinux"

- name: Install packages on Ubuntu
  become: true
  apt:
      name: "{{ packages }}"
      state: latest
  when: ansible_facts.distribution == "Ubuntu"
